# -*- coding: utf-8 -*-

from PySide2.QtWidgets import QGridLayout, QFrame, QHBoxLayout, QComboBox, QPushButton, QLabel, QVBoxLayout, QTextEdit, \
    QLineEdit, QSplitter, QTreeWidget, QProgressBar
from PySide2.QtGui import QIcon, QFont
from PySide2.QtCore import QSize, Qt, QCoreApplication


class Ui_Ulaavi(object):
    def setupUi(self, Ulaavi):
        if not Ulaavi.objectName():
            Ulaavi.setObjectName("EbroElements")
        Ulaavi.resize(1580, 953)

        self.gridLayout = QGridLayout(Ulaavi)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.frame_header = QFrame(Ulaavi)
        self.frame_header.setObjectName("frame_header")
        self.frame_header.setMaximumSize(QSize(16777215, 40))
        self.frame_header.setFocusPolicy(Qt.NoFocus)
        self.frame_header.setFrameShape(QFrame.NoFrame)
        self.frame_header.setFrameShadow(QFrame.Plain)
        self.horizontalLayout = QHBoxLayout(self.frame_header)
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout.setContentsMargins(3, 6, 0, 6)
        self.combo_group = QComboBox(self.frame_header)
        self.combo_group.setObjectName("combo_group")
        self.combo_group.setMinimumSize(QSize(140, 24))
        self.combo_group.setMaximumSize(QSize(190, 24))
        self.combo_group.setFocusPolicy(Qt.WheelFocus)
        self.combo_group.setSizeAdjustPolicy(QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.combo_group.setFrame(True)

        self.horizontalLayout.addWidget(self.combo_group)

        self.btn_add_group = QPushButton(self.frame_header)
        self.btn_add_group.setObjectName("btn_add_group")
        self.btn_add_group.setMinimumSize(QSize(24, 24))
        self.btn_add_group.setMaximumSize(QSize(24, 24))
        self.btn_add_group.setFocusPolicy(Qt.NoFocus)
        icon = QIcon()
        icon.addFile(":/icons/EbroElements/icons/plus.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_add_group.setIcon(icon)
        self.btn_add_group.setIconSize(QSize(12, 12))

        self.horizontalLayout.addWidget(self.btn_add_group)

        self.btn_remove_group = QPushButton(self.frame_header)
        self.btn_remove_group.setObjectName("btn_remove_group")
        self.btn_remove_group.setMinimumSize(QSize(24, 24))
        self.btn_remove_group.setMaximumSize(QSize(24, 24))
        self.btn_remove_group.setFocusPolicy(Qt.NoFocus)
        icon1 = QIcon()
        icon1.addFile(":/icons/EbroElements/icons/minus.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_remove_group.setIcon(icon1)
        self.btn_remove_group.setIconSize(QSize(12, 12))

        self.horizontalLayout.addWidget(self.btn_remove_group)

        self.frame_5 = QFrame(self.frame_header)
        self.frame_5.setObjectName("frame_5")
        self.frame_5.setMinimumSize(QSize(10, 0))
        self.frame_5.setMaximumSize(QSize(20, 16777215))
        self.frame_5.setFrameShape(QFrame.NoFrame)
        self.frame_5.setFrameShadow(QFrame.Raised)

        self.horizontalLayout.addWidget(self.frame_5)

        self.btn_grid_view = QPushButton(self.frame_header)
        self.btn_grid_view.setObjectName("btn_grid_view")
        self.btn_grid_view.setMinimumSize(QSize(24, 24))
        self.btn_grid_view.setMaximumSize(QSize(24, 24))
        self.btn_grid_view.setFocusPolicy(Qt.NoFocus)
        self.btn_grid_view.setStyleSheet("")
        icon2 = QIcon()
        icon2.addFile(":/icons/grid.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_grid_view.setIcon(icon2)
        self.btn_grid_view.setCheckable(True)
        self.btn_grid_view.setChecked(True)

        self.horizontalLayout.addWidget(self.btn_grid_view)

        self.btn_list_view = QPushButton(self.frame_header)
        self.btn_list_view.setObjectName("btn_list_view")
        self.btn_list_view.setMinimumSize(QSize(24, 24))
        self.btn_list_view.setMaximumSize(QSize(24, 24))
        self.btn_list_view.setFocusPolicy(Qt.NoFocus)
        self.btn_list_view.setStyleSheet("")
        icon3 = QIcon()
        icon3.addFile(":/icons/list.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_list_view.setIcon(icon3)
        self.btn_list_view.setCheckable(True)

        self.horizontalLayout.addWidget(self.btn_list_view)

        self.frame_8 = QFrame(self.frame_header)
        self.frame_8.setObjectName("frame_8")
        self.frame_8.setMinimumSize(QSize(10, 0))
        self.frame_8.setMaximumSize(QSize(14, 24))
        self.frame_8.setFrameShape(QFrame.NoFrame)
        self.frame_8.setFrameShadow(QFrame.Raised)

        self.horizontalLayout.addWidget(self.frame_8)

        self.btn_screen_capture = QPushButton(self.frame_header)
        self.btn_screen_capture.setObjectName("btn_screen_capture")
        self.btn_screen_capture.setMinimumSize(QSize(24, 24))
        self.btn_screen_capture.setMaximumSize(QSize(24, 24))
        self.btn_screen_capture.setFocusPolicy(Qt.NoFocus)
        self.btn_screen_capture.setIconSize(QSize(18, 18))

        self.horizontalLayout.addWidget(self.btn_screen_capture)

        self.frame_2 = QFrame(self.frame_header)
        self.frame_2.setObjectName("frame_2")
        self.frame_2.setMinimumSize(QSize(10, 0))
        self.frame_2.setMaximumSize(QSize(14, 16777215))
        self.frame_2.setFrameShape(QFrame.NoFrame)
        self.frame_2.setFrameShadow(QFrame.Raised)

        self.horizontalLayout.addWidget(self.frame_2)
        self.btn_refresh = QPushButton(self.frame_header)
        self.btn_refresh.setObjectName("btn_refresh")
        self.btn_refresh.setMinimumSize(QSize(24, 24))
        self.btn_refresh.setMaximumSize(QSize(24, 24))
        self.btn_refresh.setFocusPolicy(Qt.NoFocus)
        self.horizontalLayout.addWidget(self.btn_refresh)
        icon4 = QIcon()
        icon4.addFile(":/icons/refresh.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_refresh.setIcon(icon4)

        self.btn_info_global = QPushButton(self.frame_header)
        self.btn_info_global.setObjectName("btn_info_global")
        self.btn_info_global.setMinimumSize(QSize(24, 24))
        self.btn_info_global.setMaximumSize(QSize(24, 24))
        self.btn_info_global.setFocusPolicy(Qt.NoFocus)
        icon5 = QIcon()
        icon5.addFile(":/icons/info.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_info_global.setIcon(icon5)
        self.btn_info_global.setCheckable(True)

        self.horizontalLayout.addWidget(self.btn_info_global)

        self.btn_favourite = QPushButton(self.frame_header)
        self.btn_favourite.setObjectName("btn_favourite")
        self.btn_favourite.setMinimumSize(QSize(24, 24))
        self.btn_favourite.setMaximumSize(QSize(24, 24))
        self.btn_favourite.setFocusPolicy(Qt.NoFocus)
        self.btn_favourite.setStyleSheet("")
        icon6 = QIcon()
        icon6.addFile(":/icons/favorite.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_favourite.setIcon(icon6)
        self.btn_favourite.setCheckable(True)

        self.horizontalLayout.addWidget(self.btn_favourite)

        self.frame_6 = QFrame(self.frame_header)
        self.frame_6.setObjectName("frame_6")
        self.frame_6.setMinimumSize(QSize(10, 0))
        self.frame_6.setMaximumSize(QSize(20, 16777215))
        self.frame_6.setFrameShape(QFrame.NoFrame)
        self.frame_6.setFrameShadow(QFrame.Raised)

        self.horizontalLayout.addWidget(self.frame_6)

        self.combo_file_type_filter = QComboBox(self.frame_header)
        self.combo_file_type_filter.setObjectName("combo_file_type_filter")
        self.combo_file_type_filter.setMaximumSize(QSize(120, 24))
        self.horizontalLayout.addWidget(self.combo_file_type_filter)

        self.lineEdit_search = QLineEdit(self.frame_header)
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.lineEdit_search.setMinimumSize(QSize(150, 24))
        self.lineEdit_search.setMaximumSize(QSize(300, 24))
        self.lineEdit_search.setFocusPolicy(Qt.ClickFocus)
        self.lineEdit_search.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.horizontalLayout.addWidget(self.lineEdit_search)

        self.btn_search = QPushButton(self.frame_header)
        self.btn_search.setObjectName("btn_search")
        self.btn_search.setMinimumSize(QSize(24, 24))
        self.btn_search.setMaximumSize(QSize(24, 24))
        self.btn_search.setFocusPolicy(Qt.NoFocus)
        self.btn_search.setIconSize(QSize(18, 18))
        self.btn_search.setCheckable(True)

        self.horizontalLayout.addWidget(self.btn_search)

        self.frame_dummy_header = QFrame(self.frame_header)
        self.frame_dummy_header.setObjectName("frame_dummy_header")
        self.frame_dummy_header.setFrameShape(QFrame.NoFrame)
        self.frame_dummy_header.setFrameShadow(QFrame.Raised)

        self.horizontalLayout.addWidget(self.frame_dummy_header)

        self.btn_home = QPushButton(self.frame_header)
        self.btn_home.setObjectName("btn_home")
        self.btn_home.setMinimumSize(QSize(24, 24))
        self.btn_home.setMaximumSize(QSize(24, 24))
        self.btn_home.setFocusPolicy(Qt.NoFocus)
        icon7 = QIcon()
        icon7.addFile(":/icons/EbroElements/icons/home.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_home.setIcon(icon7)
        self.btn_home.setIconSize(QSize(18, 18))

        self.horizontalLayout.addWidget(self.btn_home)

        self.btn_settings = QPushButton(self.frame_header)
        self.btn_settings.setObjectName("btn_settings")
        self.btn_settings.setMinimumSize(QSize(24, 24))
        self.btn_settings.setMaximumSize(QSize(24, 24))
        self.btn_settings.setFocusPolicy(Qt.NoFocus)
        icon8 = QIcon()
        icon8.addFile(":/icons/setting.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_settings.setIcon(icon8)

        self.horizontalLayout.addWidget(self.btn_settings)

        self.frame_7 = QFrame(self.frame_header)
        self.frame_7.setObjectName("frame_7")
        self.frame_7.setMaximumSize(QSize(2, 16777215))
        self.frame_7.setFrameShape(QFrame.NoFrame)
        self.frame_7.setFrameShadow(QFrame.Raised)

        self.horizontalLayout.addWidget(self.frame_7)

        self.gridLayout.addWidget(self.frame_header, 0, 0, 1, 1)

        self.frame_footer = QFrame(Ulaavi)
        self.frame_footer.setObjectName("frame_footer")
        self.frame_footer.setMinimumSize(QSize(0, 24))
        self.frame_footer.setMaximumSize(QSize(16777215, 24))
        self.frame_footer.setFrameShape(QFrame.NoFrame)
        self.frame_footer.setFrameShadow(QFrame.Plain)
        self.horizontalLayout_6 = QHBoxLayout(self.frame_footer)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, 3)
        self.label_status_progress = QLabel(self.frame_footer)
        self.label_status_progress.setObjectName("label_status_progress")

        self.horizontalLayout_6.addWidget(self.label_status_progress)

        self.progress_bar = QProgressBar(self.frame_footer)
        self.progress_bar.setMinimumSize(120, 20)
        self.progress_bar.setMaximumSize(120, 20)
        self.horizontalLayout_6.addWidget(self.progress_bar)
        self.progress_bar.hide()

        self.gridLayout.addWidget(self.frame_footer, 2, 0, 1, 1)

        self.frame_content = QFrame(Ulaavi)
        self.frame_content.setObjectName("frame_content")
        self.frame_content.setFrameShape(QFrame.NoFrame)
        self.frame_content.setFrameShadow(QFrame.Plain)
        self.horizontalLayout_5 = QHBoxLayout(self.frame_content)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(3, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.splitter = QSplitter(self.frame_content)
        self.splitter.setObjectName("splitter")
        self.splitter.setOrientation(Qt.Horizontal)
        self.frame_content_left = QFrame(self.splitter)
        self.frame_content_left.setObjectName("frame_content_left")
        self.frame_content_left.setMinimumSize(QSize(230, 0))
        self.frame_content_left.setMaximumSize(QSize(230, 16777215))
        self.frame_content_left.setFrameShape(QFrame.NoFrame)
        self.frame_content_left.setFrameShadow(QFrame.Plain)
        self.verticalLayout_2 = QVBoxLayout(self.frame_content_left)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(3, 4, 3, 0)
        self.frame_left_content_header = QFrame(self.frame_content_left)
        self.frame_left_content_header.setObjectName("frame_left_content_header")
        self.frame_left_content_header.setMinimumSize(QSize(0, 26))
        self.frame_left_content_header.setMaximumSize(QSize(16777215, 26))
        self.frame_left_content_header.setFrameShape(QFrame.NoFrame)
        self.frame_left_content_header.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_2 = QHBoxLayout(self.frame_left_content_header)
        self.horizontalLayout_2.setSpacing(1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(9, 3, 9, 3)
        self.label_left_content_header = QLabel(self.frame_left_content_header)
        self.label_left_content_header.setObjectName("label_left_content_header")
        font = QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_left_content_header.setFont(font)

        self.horizontalLayout_2.addWidget(self.label_left_content_header)

        self.btn_category_add = QPushButton(self.frame_left_content_header)
        self.btn_category_add.setObjectName("btn_category_add")
        self.btn_category_add.setMinimumSize(QSize(20, 20))
        self.btn_category_add.setMaximumSize(QSize(20, 20))
        self.btn_category_add.setFocusPolicy(Qt.NoFocus)
        self.btn_category_add.setIcon(icon)
        self.btn_category_add.setIconSize(QSize(10, 10))

        self.horizontalLayout_2.addWidget(self.btn_category_add)

        self.btn_category_remove = QPushButton(self.frame_left_content_header)
        self.btn_category_remove.setObjectName("btn_category_remove")
        self.btn_category_remove.setMinimumSize(QSize(20, 20))
        self.btn_category_remove.setMaximumSize(QSize(20, 20))
        self.btn_category_remove.setFocusPolicy(Qt.NoFocus)
        self.btn_category_remove.setIcon(icon1)
        self.btn_category_remove.setIconSize(QSize(10, 10))

        self.horizontalLayout_2.addWidget(self.btn_category_remove)
        self.verticalLayout_2.addWidget(self.frame_left_content_header)

        self.tree_category = QTreeWidget(self.frame_content_left)
        self.tree_category.setObjectName("tree_category")
        self.tree_category.setMinimumSize(QSize(190, 0))
        self.tree_category.setMaximumSize(QSize(230, 16777215))
        self.tree_category.setFocusPolicy(Qt.StrongFocus)
        self.tree_category.setFrameShape(QFrame.NoFrame)
        self.tree_category.header().setVisible(False)
        self.tree_category.header().setDefaultSectionSize(50)

        self.verticalLayout_2.addWidget(self.tree_category)

        self.splitter.addWidget(self.frame_content_left)
        self.frame_thumb_loader = QFrame(self.splitter)
        self.frame_thumb_loader.setObjectName("frame_thumb_loader")
        self.frame_thumb_loader.setMaximumSize(QSize(16777215, 16777215))
        self.frame_thumb_loader.setFrameShape(QFrame.NoFrame)
        self.frame_thumb_loader.setFrameShadow(QFrame.Plain)
        self.horizontalLayout_4 = QHBoxLayout(self.frame_thumb_loader)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(0, 0, 6, 0)
        self.horizontalLayout_4.setSpacing(0)
        font1 = QFont()
        font1.setPointSize(10)
        font1.setBold(False)
        font1.setWeight(50)

        self.splitter.addWidget(self.frame_thumb_loader)
        self.frame_content_right = QFrame(self.splitter)
        self.frame_content_right.setObjectName("frame_content_right")
        self.frame_content_right.setMinimumSize(QSize(150, 0))
        self.frame_content_right.setMaximumSize(QSize(450, 16777215))
        self.frame_content_right.setFrameShape(QFrame.NoFrame)
        self.frame_content_right.setFrameShadow(QFrame.Plain)
        self.verticalLayout = QVBoxLayout(self.frame_content_right)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.frame_preview = QFrame(self.frame_content_right)
        self.frame_preview.setObjectName("frame_preview")
        self.frame_preview.setFrameShape(QFrame.NoFrame)
        self.frame_preview.setFrameShadow(QFrame.Plain)

        self.verticalLayout.addWidget(self.frame_preview)

        self.frame_info = QFrame(self.frame_content_right)
        self.frame_info.setObjectName("frame_info")
        self.frame_info.setFrameShape(QFrame.NoFrame)
        self.frame_info.setFrameShadow(QFrame.Plain)

        self.verticalLayout.addWidget(self.frame_info)

        self.splitter.addWidget(self.frame_content_right)

        self.horizontalLayout_5.addWidget(self.splitter)
        self.gridLayout.addWidget(self.frame_content, 1, 0, 1, 1)
        self.btn_grid_view.hide()
        self.btn_list_view.hide()
        self.frame_preview.hide()
        self.info_text = QTextEdit()
        self.info_layout = QHBoxLayout(self.frame_info)
        self.info_layout.addWidget(self.info_text)
        self.info_layout.setContentsMargins(0, 0, 0, 0)
        self.info_text.setFrameShape(QFrame.NoFrame)

        self.setWindowTitle(QCoreApplication.translate("Ulaavi", "Ulaavi v1.0", None))
        self.lineEdit_search.setPlaceholderText(QCoreApplication.translate("Ulaavi", "Search", None))
        self.label_left_content_header.setText(QCoreApplication.translate("Ulaavi", "Category", None))
        ___qtreewidgetitem = self.tree_category.headerItem()
        ___qtreewidgetitem.setText(0, QCoreApplication.translate("Ulaavi", "Item", None));

